// Shared Nepali vocabulary data — used by both reading.js and quiz.js

const QUIZ_WORDS = [
    { np: 'म', en: 'I / me', roman: 'ma' },
    { np: 'तिमी', en: 'you (informal)', roman: 'timī' },
    { np: 'तपाईं', en: 'you (formal)', roman: 'tapāīṁ' },
    { np: 'उ', en: 'he / she', roman: 'u' },
    { np: 'हामी', en: 'we', roman: 'hāmī' },
    { np: 'यो', en: 'this', roman: 'yo' },
    { np: 'त्यो', en: 'that', roman: 'tyo' },
    { np: 'के', en: 'what', roman: 'ke' },
    { np: 'को', en: 'who', roman: 'ko' },
    { np: 'कहाँ', en: 'where', roman: 'kahā̃' },
    { np: 'कसरी', en: 'how', roman: 'kasarī' },
    { np: 'किन', en: 'why', roman: 'kina' },
    { np: 'कति', en: 'how much / how many', roman: 'kati' },
    { np: 'कहिले', en: 'when', roman: 'kahile' },
    { np: 'हो', en: 'is (affirmative)', roman: 'ho' },
    { np: 'छ', en: 'is / exists', roman: 'cha' },
    { np: 'छैन', en: 'is not', roman: 'chaina' },
    { np: 'थियो', en: 'was', roman: 'thiyo' },
    { np: 'हुन्छ', en: 'will be / okay', roman: 'huncha' },
    { np: 'गर्नु', en: 'to do', roman: 'garnu' },
    { np: 'जानु', en: 'to go', roman: 'jānu' },
    { np: 'आउनु', en: 'to come', roman: 'āunu' },
    { np: 'खानु', en: 'to eat', roman: 'khānu' },
    { np: 'पिउनु', en: 'to drink', roman: 'piunu' },
    { np: 'हेर्नु', en: 'to look / see', roman: 'hernu' },
    { np: 'बोल्नु', en: 'to speak', roman: 'bolnu' },
    { np: 'सुन्नु', en: 'to listen / hear', roman: 'sunnu' },
    { np: 'पढ्नु', en: 'to read / study', roman: 'paḍhnu' },
    { np: 'लेख्नु', en: 'to write', roman: 'lekhnu' },
    { np: 'बस्नु', en: 'to sit / live', roman: 'basnu' },
    { np: 'दिनु', en: 'to give', roman: 'dinu' },
    { np: 'लिनु', en: 'to take', roman: 'linu' },
    { np: 'राम्रो', en: 'good / nice', roman: 'rāmro' },
    { np: 'नराम्रो', en: 'bad', roman: 'narāmro' },
    { np: 'ठूलो', en: 'big', roman: 'ṭhūlo' },
    { np: 'सानो', en: 'small', roman: 'sāno' },
    { np: 'नयाँ', en: 'new', roman: 'nayā̃' },
    { np: 'पुरानो', en: 'old (thing)', roman: 'purāno' },
    { np: 'धेरै', en: 'many / much / very', roman: 'dherai' },
    { np: 'अलि', en: 'a little', roman: 'ali' },
    { np: 'अहिले', en: 'now', roman: 'ahile' },
    { np: 'भोलि', en: 'tomorrow', roman: 'bholi' },
    { np: 'हिजो', en: 'yesterday', roman: 'hijo' },
    { np: 'आज', en: 'today', roman: 'āj' },
    { np: 'दिन', en: 'day', roman: 'din' },
    { np: 'रात', en: 'night', roman: 'rāt' },
    { np: 'घर', en: 'house / home', roman: 'ghar' },
    { np: 'मान्छे', en: 'person', roman: 'mānchhe' },
    { np: 'नाम', en: 'name', roman: 'nām' },
    { np: 'काम', en: 'work', roman: 'kām' },
    { np: 'पानी', en: 'water', roman: 'pānī' },
    { np: 'खाना', en: 'food', roman: 'khānā' },
    { np: 'बाटो', en: 'road / way', roman: 'bāṭo' },
    { np: 'पैसा', en: 'money', roman: 'paisā' },
    { np: 'समय', en: 'time', roman: 'samay' },
    { np: 'देश', en: 'country', roman: 'desh' },
    { np: 'नेपाल', en: 'Nepal', roman: 'nepāl' },
    { np: 'भाषा', en: 'language', roman: 'bhāṣā' },
    { np: 'किताब', en: 'book', roman: 'kitāb' },
    { np: 'विद्यालय', en: 'school', roman: 'vidyālay' },
    { np: 'बच्चा', en: 'child', roman: 'bacchā' },
    { np: 'आमा', en: 'mother', roman: 'āmā' },
    { np: 'बुबा', en: 'father', roman: 'bubā' },
    { np: 'दिदी', en: 'elder sister', roman: 'didī' },
    { np: 'दाइ', en: 'elder brother', roman: 'dāi' },
    { np: 'साथी', en: 'friend', roman: 'sāthī' },
    { np: 'मन', en: 'heart / mind', roman: 'man' },
    { np: 'र', en: 'and', roman: 'ra' },
    { np: 'तर', en: 'but', roman: 'tara' },
    { np: 'पनि', en: 'also / too', roman: 'pani' },
    { np: 'मात्र', en: 'only', roman: 'mātra' },
    { np: 'सबै', en: 'all / everyone', roman: 'sabai' },
    { np: 'एक', en: 'one', roman: 'ek' },
    { np: 'दुई', en: 'two', roman: 'duī' },
    { np: 'तीन', en: 'three', roman: 'tīn' },
    { np: 'चार', en: 'four', roman: 'chār' },
    { np: 'पाँच', en: 'five', roman: 'pā̃ch' },
    { np: 'दश', en: 'ten', roman: 'dash' },
    { np: 'खुसी', en: 'happy', roman: 'khusī' },
    { np: 'सुन्दर', en: 'beautiful', roman: 'sundar' },
    { np: 'ठीक', en: 'okay / fine', roman: 'ṭhīk' },
    { np: 'माया', en: 'love', roman: 'māyā' },
    { np: 'धन्यवाद', en: 'thank you', roman: 'dhanyavād' },
];

const QUIZ_PHRASES = [
    { np: 'नमस्ते हजुर', en: 'Hello (respectful)', roman: 'namaste hajur' },
    { np: 'सुप्रभात हजुर', en: 'Good morning (respectful)', roman: 'suprabhāt hajur' },
    { np: 'शुभ रात्री', en: 'Good night', roman: 'shubha rātrī' },
    { np: 'माफ गर्नुहोस्', en: 'Excuse me / Sorry', roman: 'māf garnuhos' },
    { np: 'कस्तो छ?', en: 'How are you?', roman: 'kasto cha?' },
    { np: 'सञ्चै छु', en: 'I am fine', roman: 'sañchai chu' },
    { np: 'फेरि भेटौँला', en: 'See you again', roman: 'pheri bheṭaũlā' },
    { np: 'मेरो नाम', en: 'My name', roman: 'mero nām' },
    { np: 'तपाईंको नाम', en: 'Your name', roman: 'tapāīṅko nām' },
    { np: 'घर जानु', en: 'Go home', roman: 'ghar jānu' },
    { np: 'पानी दिनुहोस्', en: 'Please give water', roman: 'pānī dinuhos' },
    { np: 'कति पर्छ?', en: 'How much does it cost?', roman: 'kati parcha?' },
    { np: 'ठीक छ', en: "It's okay", roman: 'ṭhīk cha' },
    { np: 'थाहा छैन', en: "I don't know", roman: 'thāhā chaina' },
    { np: 'राम्रो भयो', en: "That's good", roman: 'rāmro bhayo' },
    { np: 'खाना खानु', en: 'Eat food', roman: 'khānā khānu' },
    { np: 'चिया पिउनु', en: 'Drink tea', roman: 'chiyā piunu' },
    { np: 'काम गर्नु', en: 'Do work', roman: 'kām garnu' },
    { np: 'किताब पढ्नु', en: 'Read a book', roman: 'kitāb paḍhnu' },
    { np: 'बजार जानु', en: 'Go to market', roman: 'bajār jānu' },
    { np: 'बिहान उठ्नु', en: 'Wake up in the morning', roman: 'bihān uṭhnu' },
    { np: 'साथी भेट्नु', en: 'Meet a friend', roman: 'sāthī bheṭnu' },
];
